// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Security.Persistence.Context;

#nullable disable

namespace Security.Persistence.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240509131033_PersonelForDbContex")]
    partial class PersonelForDbContex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PersonelUnit", b =>
                {
                    b.Property<int>("PersonelsId")
                        .HasColumnType("int");

                    b.Property<int>("unitsId")
                        .HasColumnType("int");

                    b.HasKey("PersonelsId", "unitsId");

                    b.HasIndex("unitsId");

                    b.ToTable("PersonelUnit");
                });

            modelBuilder.Entity("Security.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchName = "İdari Mali İşler Şube Müdürlüğü",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            BranchName = "Destek Hizmetleri Şube Müdürlüğü",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            BranchName = "Personel Şube Müdürlüğü",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            BranchName = "Eğitim Şube Müdürlüğü",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            BranchName = "Öğrenci İşleri Şube Müdürlüğü",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            BranchName = "Pomem Şube Müdürlüğü",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Security.Domain.Entities.BranchAndUnitRelationShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("UnitId");

                    b.ToTable("BranchAndUnitRelationShips");
                });

            modelBuilder.Entity("Security.Domain.Entities.CarPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonel")
                        .HasColumnType("bit");

                    b.Property<string>("PlateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarPlates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 351, DateTimeKind.Local).AddTicks(5277),
                            IsDeleted = false,
                            IsPersonel = true,
                            PlateName = "69 AAA 13"
                        },
                        new
                        {
                            Id = 2,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 351, DateTimeKind.Local).AddTicks(5290),
                            IsDeleted = false,
                            IsPersonel = false,
                            PlateName = "69 AB 25"
                        },
                        new
                        {
                            Id = 3,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 351, DateTimeKind.Local).AddTicks(5291),
                            IsDeleted = false,
                            IsPersonel = true,
                            PlateName = "25 ACH 361"
                        },
                        new
                        {
                            Id = 4,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 351, DateTimeKind.Local).AddTicks(5292),
                            IsDeleted = false,
                            IsPersonel = false,
                            PlateName = "34 PLK 45"
                        },
                        new
                        {
                            Id = 5,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 351, DateTimeKind.Local).AddTicks(5292),
                            IsDeleted = false,
                            IsPersonel = false,
                            PlateName = "69 AS 89"
                        });
                });

            modelBuilder.Entity("Security.Domain.Entities.Identity.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Security.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Security.Domain.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00cf295d-0182-4e4f-9ca5-07de0278869d",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea2208d0-96d0-47b8-887d-2971aed6ca8e",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20a42d2d-0fc0-4b5c-aaa2-2e8e37532d18",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "875a0986-b37b-4277-afd6-37331189d9cf",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7643b32d-148c-4b84-b7c3-c38efaf7c5c0",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = true,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80aec085-d3fd-438f-960b-64e37ac91dbe",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44325c18-0c4c-47b6-81b4-b0af084de62e",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1bbcf8d0-6bf4-4ac2-9810-a2e3e821d4ad",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee7bbed2-869a-4678-af3e-391c57f0341e",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = false,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eb32c43d-ed65-41a0-828f-2db6642fca95",
                            EmailConfirmed = false,
                            FirstName = "Şadan",
                            IsDeleted = true,
                            LastName = "Çamdalı",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Security.Domain.Entities.PersonelEntities.PersonelChartOfAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonelChartOfAccounts", (string)null);
                });

            modelBuilder.Entity("Security.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            IsDeleted = false,
                            UnitName = "Satın Alma Büro Amirliği"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            IsDeleted = false,
                            UnitName = "Tahakkuk Büro Amirliği"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 2,
                            IsDeleted = false,
                            UnitName = "Atış Büro Amirliği"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 3,
                            IsDeleted = false,
                            UnitName = "Personel Kayıt Amirliği"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 4,
                            IsDeleted = false,
                            UnitName = "Öğrenci Özlük Amirliği"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 6,
                            IsDeleted = false,
                            UnitName = "Belge Yönetimi Amirliği"
                        });
                });

            modelBuilder.Entity("Security.Domain.Entities.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CarPlateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("JobInterview")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<bool>("Visit")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(1014),
                            FirstName = "Özden",
                            IdentityNumber = "195605050599",
                            IsDeleted = false,
                            JobInterview = true,
                            LastName = "Aybar",
                            PersonelId = 1,
                            Visit = false
                        },
                        new
                        {
                            Id = 2,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3592),
                            FirstName = "Özden",
                            IdentityNumber = "195605050599",
                            IsDeleted = false,
                            JobInterview = true,
                            LastName = "Aybar",
                            PersonelId = 1,
                            ReleaseDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3601),
                            UnitId = 2,
                            Visit = false
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 3,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3604),
                            FirstName = "Özden",
                            IdentityNumber = "195605050599",
                            IsDeleted = true,
                            JobInterview = true,
                            LastName = "Aybar",
                            PersonelId = 1,
                            Visit = false
                        },
                        new
                        {
                            Id = 4,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3607),
                            FirstName = "Özden",
                            IdentityNumber = "195605050599",
                            IsDeleted = false,
                            JobInterview = true,
                            LastName = "Aybar",
                            PersonelId = 1,
                            ReleaseDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3609),
                            UnitId = 4,
                            Visit = false
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 2,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3610),
                            FirstName = "Özden",
                            IdentityNumber = "195605050599",
                            IsDeleted = false,
                            JobInterview = true,
                            LastName = "Aybar",
                            PersonelId = 1,
                            ReleaseDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3612),
                            Visit = false
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 5,
                            EntryDate = new DateTime(2024, 5, 9, 16, 10, 32, 356, DateTimeKind.Local).AddTicks(3613),
                            FirstName = "Özden",
                            IdentityNumber = "195605050599",
                            IsDeleted = true,
                            JobInterview = true,
                            LastName = "Aybar",
                            PersonelId = 1,
                            Visit = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Security.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Security.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Security.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Security.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Security.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Security.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonelUnit", b =>
                {
                    b.HasOne("Security.Domain.Entities.Personel", null)
                        .WithMany()
                        .HasForeignKey("PersonelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Security.Domain.Entities.Unit", null)
                        .WithMany()
                        .HasForeignKey("unitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Security.Domain.Entities.BranchAndUnitRelationShip", b =>
                {
                    b.HasOne("Security.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Security.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Security.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Branch");

                    b.Navigation("Personel");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Security.Domain.Entities.Unit", b =>
                {
                    b.HasOne("Security.Domain.Entities.Branch", "Branch")
                        .WithMany("Units")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Security.Domain.Entities.Visitor", b =>
                {
                    b.HasOne("Security.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Security.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
